# Generated by Django 4.1.7 on 2023-03-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0002_songs_delete_cacheentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('playlist_title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'playlists',
            },
        ),
        migrations.RenameField(
            model_name='songs',
            old_name='title',
            new_name='song_title',
        ),
        migrations.AddField(
            model_name='songs',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yt_search.playlists'),
            preserve_default=False,
        ),
    ]
