# Generated by Django 4.1.7 on 2023-03-05 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0003_playlists_rename_title_songs_song_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='playlist',
            field=models.ForeignKey(default="none's playlist", on_delete=django.db.models.deletion.CASCADE, to='yt_search.playlists'),
        ),
    ]
