# Generated by Django 4.1.7 on 2023-03-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0006_playlists_playlist_link_playlists_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='user_id',
        ),
        migrations.AddField(
            model_name='playlists',
            name='uuid',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
