# Generated by Django 4.1.7 on 2023-03-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0007_remove_usertoken_user_id_playlists_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='uuid',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
